### ISSUE TITLE
Adapt src/openssl.cnf.sample file for new openssl version

### ISSUE THREAD

**Issue by chrisRund** [opencryptoki/openssl-ibmca#61]
The definition of the ibmca engine for openssl 1.1 changed from openssl_conf = openssl_def to 
openssl_conf = default_modules

[ default_modules ]
engines = engine_section
Please work this change into the openssl.cnf.sample file.
Thanks.

**Comment by p-steuer** [comment]
Both "openssl_def" and "default_modules" are just variable names for the sections chosen by whoever writes an openssl config file.

Since we provide a _sample_ openssl config i dont see a reason to use always use the same name as in some distribution's global openssl conf. The point is different openssl.confs may use different names here and we cannot make everyone happy.
